# ======================================================================================================================
# LOCAL - DEFAULT PROFILE
# ======================================================================================================================
server:
  port: 8001
  error:
    include-message: always

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.hausenn.com.br/auth/realms/hausenn/protocol/openid-connect/certs